### PR TITLE
replaced installreferrer-1.0.aar with Xamarin.Android.Binding.InstallReferrer 2.2.0

### LINKED ISSUE #32: Android: installreferrer-1.0.aar is referenced instead of nuget Xamarin.Android.Binding.InstallReferrer
May lead to the build error given below when the adjust sdk is referenced side by side with another nuget which depends on `Xamarin.Android.Binding.InstallReferrer`:

`Xamarin.Android.Common.targets(1456, 3): [XA4215] The Java type mono.com.android.installreferrer.api.InstallReferrerStateListenerImplementor is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.`

### PR DESCRIPTION
**Pull request by thisisthekap**
fixes #32

### CODE REVIEW

**Comment by uerceg** [comment]
Hey @thisisthekap 

And thanks for the PR! It looks pretty nice. However, we unfortunately can't do this right now because this adds dependency of our SDK to 3rd party library which is against our policies. With all due respect to Douglas Giovanella who created the plugin which seems pretty nice, but we just can't create dependency of our SDK to that library.

Do you have a way to access to JAR file which our plugin is importing when you add it? If you have, in theory you can feel free to remove it from your app and install referrer functionality will still work just fine because `Xamarin.Android.Binding.InstallReferrer` will make sure that install referrer library is present inside of your app.

**Comment by thisisthekap** [comment]
Hi @uerceg

Thank you for the fast response!

Our app is not referencing Xamarin.Android.Binding.InstallReferrer directly.

Another dependency which binds an android library is referencing Xamarin.Android.Binding.InstallReferrer.

Without the changes given in my PR, referencing both the other android library and the adjust SDK breaks the compilation.

I understand that you need to avoid 3rd party libraries.

But to my point of view, the referenced aar file is a 3rd party dependency.

Therefore, Xamarin.Android.Binding.InstallReferrer would just add a tiny binding layer which is available open source, and which should pose no licensing issues.

**Comment by uerceg** [comment]
Hi @thisisthekap 

I see. Technically what you are saying is correct (that install referrer AAR is third party dependency), but it's a dependency which is needed for pretty important part of Adjust ecosystem for which SDK is providing info by reading information from this Google's library. And AAR we are adding is built by Google, so again with all due respect to plugin creator, depending on core dependency built by their creators is something we chose to go with.

There are also aspects of this decision which are not related just to software development. For example many clients would not feel comfortable with having dependency to some 3rd party library like this. Or another example might be licensing topic. If you check repository of `Xamarin.Android.Binding.InstallReferrer` plugin, there's no license text mentioned anywhere. And dependency to such component brings actual legal issues for some clients. And even if this library was licensed under MIT license, we have no guarantee that maybe one day it will stop being licensed with MIT license, but maybe some other more restrictive which will again cause legal issues for our clients.

So with all these things in mind, we simply can't do this.

**Comment by thisisthekap** [comment]
Ok, got your point.

Would it be a feasible option that you publish a nuget similar to the one in question yourself?

I even would be happy to include it in my PR.

**Comment by uerceg** [comment]
In theory we can do this on our own, yes. But unfortunately I can't give you any ETA on when we would be able to have this done and pushed to NuGet.

**Comment by thisisthekap** [comment]
As mentioned, I would be happy to provide the project binding the installreferrer to xamarin.

**Comment by uerceg** [comment]
Oh, that would be great beyond doubt amazing contribution. If you're willing to do that, I'd advise to open `AdjustSdk.Xamarin.Android.sln` solution and in there add new binding project in same way how we added `AdjustSdk.Xamarin.Android`. Not really sure about project name, but let's say as starting point to name it `Adjust.Xamarin.Android.InstallReferrer`.

**Comment by thisisthekap** [comment]
Sounds good. I am going to do so next week. Are you going to be able to create and publish the nuget in a timely manner?

**Comment by uerceg** [comment]
Yep, we'll try to do that as soon as possible. One thing which I am now thinking about is if this setup will cause breaking changes in integration of our SDK. Currently there are two ways (well, three, but doubt that anyone is using third):
1. Via NuGet.
2. Downloading and adding DLL we publish in releases pages.
3. Downloading source code an adding our binding project directly (doubt anyone is doing this).

If we're about to kick install referrer AAR out if Xamarin SDK, question is will integration for first two cases remain the same.
1. From what I see in your PR, stating that our SDK NuGet package pulls dependency on to-be-created install referrer NuGet package should have this use case covered, right? Meaning that people will not need to add separately SDK and install referrer NuGet package?
2. We need to make sure that DLL we're providing to users in upcoming v4.x.y releases still contains everything under the hood (including install referrer library) because we don't want to generate new binding DLL of install referrer. We don't want to do this because we have policy of non breaking API and integration changes within same major version. Would this still be possible with changes you plan to make?

**Comment by thisisthekap** [comment]
The first scenario should work as expected, because the installreferrer lib is referenced and restored in a transitive way.

I am not sure about the second one. There are tools like ilmerge out there, but I do not know if they are usable for xamarin android binding projects. Could you assist on that?

**Comment by thisisthekap** [comment]
Converted to draft, because https://github.com/adjust/xamarin_sdk/issues/32 is blocking this issue.

It is quite likely, that users using the Adjust SDK are using the Facebook SDK alongside.

**Comment by thisisthekap** [comment]
Converted to draft, because installreferrer binding project is missing.

**Comment by thisisthekap** [comment]
@uerceg Adjust.Xamarin.Android.InstallReferrer was added.

**Comment by thisisthekap** [comment]
@uerceg Can you already provide me an update on the publishing of the Adjust.Xamarin.Android.InstallReferrer nuget?

**Comment by uerceg** [comment]
Hi @thisisthekap 

Hopefully I'll be able to take a look at the PR by end of this week and have some update to share at the beginning of next week.

**Comment by thisisthekap** [comment]
@uerceg Any update?

**Comment by thisisthekap** [comment]
@uerceg Any update on this one?

**Comment by uerceg** [comment]
Hey, sorry for delay. Unfortunately, we ended up with some more urgent tasks we needed to push through and had no time to check this. We have it in our queue for next week. Sorry for not being able to take a look sooner and thank you one more time for your contribution!

**Comment by thisisthekap** [comment]
@uerceg I understand that timetables can be tight :)

Anyway, this one is blocking https://github.com/xamarin/FacebookComponents/issues/194, which is blocking the update of the Facebook android sdk to the most recent version.

**Comment by thisisthekap** [comment]
@uerceg Any update?

**Comment by thisisthekap** [comment]
@uerceg @2beens As my facebook components PRs are currently in review, and the missing install referrer nuget definitely poses an issue there, any progress on this PR would be very much appreciated!

**Comment by uerceg** [comment]
Hi @thisisthekap 

Sorry for delay on our end and thank you one more for your contribution and patience.

I am looking at this PR now and I am not sure if we are going to be able to proceed with this change officially. Problem which I am noticing is pretty much that [bullet point 2](https://github.com/adjust/xamarin_sdk/pull/33#issuecomment-765682342) from comment above. We have clients who are using our SDK simply by importing DLL libraries which we are uploading to each release here in GitHub release pages. And moving install referrer library outside of our SDK would simply break integration for these users. With these changes, we would have Adjust Android binding DLL now without install referrer library and we would need to generate new DLL for install referrer binding project and clients would need to add both in their app in order to maintain same functionality which they currently have with this "fat" binding of ours.

We unfortunately can't make this move, at least not while we're still with SDK v4.x.y. The day we make next major SDK update, that's gonna be moment in which we can introduce breaking changes and among others, this one as well. I definitely understand the motivation behind this solution and in general I think that solution is actually pretty nice and makes sense, but for a little while we unfortunately need to keep things as they are. Install referrer and information which that library provides is in absolute core of Adjust (and any other MMP) business since it's really important for attribution and we just don't have the luxury to introduce breaking integration changes within same major SDK version and risk that clients miss this information in SDK update and cause their marketing campaigns to be severely hit because of that.

I think that in theory we can release Adjust binding for install referrer into NuGet repo, but again I don't think it makes much sense for this particular use case since main SDK itself will still contain install referrer library bundled inside.

**Comment by thisisthekap** [comment]
This makes it impossible for developers to use the adjust xamarin android sdk and the facebook xamarin android sdk side by side.

So this is not some nice to have solution for cleaner project structure. It is a fix to a issue which is blocking for the described scenario.

A possible solution I could think of would be to publish a "thin" adjust sdk which referenced Xamarin.Android.InstallReferrer without removing/replacing . This would maintain compatibility, while providing a fix to this issue. What do you think?

**Comment by uerceg** [comment]
I understand. But also when thinking about it and the fact that install referrer libraries are conflicting and causing duplicated symbol errors, does that also mean that FB is taking pretty much same approach and has install referrer library being part of their own SDK?

Idea you have is not bad, but I am not really sure we can have this prioritised on our end to be done anytime soon.

**Pull request closed without merging**
